//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprice_personell_department
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPDEntities : DbContext
    {
        private static EPDEntities _context;
        public EPDEntities()
            : base("name=EPDEntities")
        {
        }

        public static EPDEntities GetContext()
        {
            if (_context == null)
                _context = new EPDEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Адрес> Адрес { get; set; }
        public virtual DbSet<ВидРаботы> ВидРаботы { get; set; }
        public virtual DbSet<ВидРодства> ВидРодства { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Образование> Образование { get; set; }
        public virtual DbSet<ПаспортныеДанные> ПаспортныеДанные { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Токен> Токен { get; set; }
        public virtual DbSet<ЧленыСемьиСотрудника> ЧленыСемьиСотрудника { get; set; }
    }
}
