//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprice_personell_department
{
    using System;
    using System.Collections.Generic;
    
    public partial class ВидРодства
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ВидРодства()
        {
            this.ЧленыСемьиСотрудника = new HashSet<ЧленыСемьиСотрудника>();
        }
    
        public int id_ВидаРодства { get; set; }
        public string СтепеньРодства { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЧленыСемьиСотрудника> ЧленыСемьиСотрудника { get; set; }
    }
}
