//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprice_personell_department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Образование
    {
        public int id_Образования { get; set; }
        public int id_Сотрудника { get; set; }
        public string НазваниеУчебнойОрганизации { get; set; }
        public string УровеньОбразование { get; set; }
        public string СерияНомерДиплома { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public string Специальность { get; set; }
        public string Квалификация { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
