//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprice_personell_department
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПаспортныеДанные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПаспортныеДанные()
        {
            this.Сотрудник = new HashSet<Сотрудник>();
        }
    
        public int id_Паспорта { get; set; }
        public string НомерСерияПаспорта { get; set; }
        public string КемВыдан { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public string КодПодразделения { get; set; }
        public string МестоРождения { get; set; }
        public string МестоЖительства { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }
    }
}
