//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprice_personell_department
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Образование = new HashSet<Образование>();
            this.ЧленыСемьиСотрудника = new HashSet<ЧленыСемьиСотрудника>();
        }
    
        public int id_Сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string Пол { get; set; }
        public string Гражданство { get; set; }
        public string Телефон { get; set; }
        public int id_Адреса { get; set; }
        public int id_Должности { get; set; }
        public int id_Паспорта { get; set; }
        public int id_Договора { get; set; }
        public string Фото { get; set; }
    
        public virtual Адрес Адрес { get; set; }
        public virtual Договор Договор { get; set; }
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Образование> Образование { get; set; }
        public virtual ПаспортныеДанные ПаспортныеДанные { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЧленыСемьиСотрудника> ЧленыСемьиСотрудника { get; set; }
    }
}
